[package]
name = "snippy-common"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "2.0.1"
anyhow = "1.0.98"
blake3 = "1.8.2"
sysinfo = { version = "0.35.2", features = ["multithread"] }
once_cell = "1.21.3"
num_cpus = "1.17.0"
