# compress/Cargo.toml
[package]
name = "compress"
version = "0.1.0"
edition = "2021"

[dependencies]
walkdir = "2"
zstd = "0.13"
blake3 = "1"
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
rayon = "1.10"
anyhow = "1"
hex = "0.4"
